version: '3.3'
services:

  senzing-eval-tool-app-web:
    container_name: senzing-eval-tool-app-web
 #   command: "node ./run/scripts/start-webserver"
    environment:
      SENZING_API_SERVER_URL: http://senzing-api-server:8250
      SENZING_GRPC_CONNECTION_STRING: http://localhost:8260/grpc
      SENZING_WEB_SERVER_ADMIN_AUTH_MODE: JWT
      SENZING_WEB_SERVER_ADMIN_AUTH_PATH: http://senzing-eval-tool-app-web:8260
      SENZING_WEB_SERVER_API_PATH: '/api'
      SENZING_WEB_SERVER_PORT: 8263
    image: senzing/eval-tool-app-web:${SENZING_DOCKER_IMAGE_VERSION_EVAL_TOOL_APP_WEB:-latest}
    networks:
      - senzing
    ports:
      - 8262:8260
      - 8263:8263
      - 8257:8257
    read_only: true
    restart: 'always'

networks:
  senzing:
    external: true
    name: ${SENZING_DOCKER_NETWORK:-senzing-network}
